# Text Representation - Bag Of Words (BOW)

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("Spam.csv")

In [3]:
df

Category                                            Message
0         ham  Go until jurong point, crazy.. Available only ...
1         ham                      Ok lar... Joking wif u oni...
2        spam  Free entry in 2 a wkly comp to win FA Cup fina...
3         ham  U dun say so early hor... U c already then say...
4         ham  Nah I don't think he goes to usf, he lives aro...
...       ...                                                ...
5567     spam  This is the 2nd time we have tried 2 contact u...
5568      ham               Will ü b going to esplanade fr home?
5569      ham  Pity, * was in mood for that. So...any other s...
5570      ham  The guy did some bitching but I acted like i'd...
5571      ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [6]:
df.Category.value_counts()

ham     4825
spam     747
Name: Category, dtype: int64

In [8]:
df["Spam"] = df["Category"].apply(lambda x : 1 if x == "spam" else 0)

In [9]:
df

Category                                            Message  Spam
0         ham  Go until jurong point, crazy.. Available only ...     0
1         ham                      Ok lar... Joking wif u oni...     0
2        spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3         ham  U dun say so early hor... U c already then say...     0
4         ham  Nah I don't think he goes to usf, he lives aro...     0
...       ...                                                ...   ...
5567     spam  This is the 2nd time we have tried 2 contact u...     1
5568      ham               Will ü b going to esplanade fr home?     0
5569      ham  Pity, * was in mood for that. So...any other s...     0
5570      ham  The guy did some bitching but I acted like i'd...     0
5571      ham                         Rofl. Its true to its name     0

[5572 rows x 3 columns]

In [12]:
df.drop("Category",axis = 1)

Message  Spam
0     Go until jurong point, crazy.. Available only ...     0
1                         Ok lar... Joking wif u oni...     0
2     Free entry in 2 a wkly comp to win FA Cup fina...     1
3     U dun say so early hor... U c already then say...     0
4     Nah I don't think he goes to usf, he lives aro...     0
...                                                 ...   ...
5567  This is the 2nd time we have tried 2 contact u...     1
5568               Will ü b going to esplanade fr home?     0
5569  Pity, * was in mood for that. So...any other s...     0
5570  The guy did some bitching but I acted like i'd...     0
5571                         Rofl. Its true to its name     0

[5572 rows x 2 columns]

In [13]:
df.shape

(5572, 3)

## Train test split

In [15]:
from sklearn.model_selection import train_test_split

In [26]:
x_train,x_test,y_train,y_test = train_test_split(df["Message"],df["Spam"],test_size=0.2)

In [27]:
x_train.shape

(4457,)

In [28]:
x_test.shape

(1115,)

In [29]:
type(x_train)


pandas.core.series.Series

##  bag of words (BOW's)representation using CountVectorizer

In [30]:
from sklearn.feature_extraction.text import CountVectorizer

v = CountVectorizer()

X_train_cv = v.fit_transform(x_train.values)


In [35]:
import numpy as np

In [39]:
X_train_cv.toarray()[:4][0]

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [41]:
X_train_cv.shape

(4457, 7733)

In [45]:
v.get_feature_names_out()

array(['00', '000', '000pes', ..., 'èn', 'ú1', '〨ud'], dtype=object)

In [43]:
v.vocabulary_

{'eh': 2553,
 'sorry': 6322,
 'leh': 4081,
 'din': 2327,
 'ur': 7187,
 'msg': 4628,
 'not': 4835,
 'sad': 5866,
 'already': 923,
 'lar': 4028,
 'me': 4419,
 'watching': 7384,
 'tv': 7067,
 'now': 4849,
 'still': 6482,
 'in': 3652,
 'office': 4907,
 'get': 3128,
 'ready': 5607,
 'to': 6920,
 'put': 5513,
 'on': 4940,
 'your': 7701,
 'excellent': 2697,
 'sub': 6545,
 'face': 2746,
 'am': 933,
 'tirupur': 6900,
 'da': 2147,
 'once': 4943,
 'you': 7696,
 'started': 6447,
 'from': 3028,
 'call': 1609,
 'just': 3884,
 're': 5596,
 'read': 5603,
 'it': 3772,
 'and': 958,
 'have': 3366,
 'no': 4799,
 'shame': 6054,
 'but': 1576,
 'tell': 6744,
 'how': 3528,
 'he': 3375,
 'takes': 6684,
 'if': 3610,
 'runs': 5855,
 'will': 7507,
 'blame': 1373,
 'ever': 2671,
 'really': 5616,
 'long': 4205,
 'time': 6887,
 'thanx': 6798,
 'my': 4675,
 'birthday': 1359,
 'is': 3761,
 'over': 5037,
 'ill': 3622,
 'be': 1263,
 'there': 6819,
 'lt': 4262,
 'gt': 3270,
 'ok': 4920,
 'hey': 3428,
 'mr': 4624,
 'whats

In [46]:
v.get_feature_names_out()[2553]

'eh'

## Train the naive bayes model

In [48]:
from sklearn.naive_bayes import MultinomialNB

model = MultinomialNB()
model.fit(X_train_cv, y_train)

MultinomialNB()

In [50]:
X_test_cv = v.transform(x_test)

In [52]:
X_test_cv.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [53]:
from sklearn.metrics import classification_report

y_pred = model.predict(X_test_cv)

print(classification_report(y_test, y_pred))  # use classification_report when their is bais dataset

              precision    recall  f1-score   support

           0       0.99      0.99      0.99       956
           1       0.97      0.92      0.95       159

    accuracy                           0.98      1115
   macro avg       0.98      0.96      0.97      1115
weighted avg       0.98      0.98      0.98      1115



In [54]:
model.predict(X_test_cv)

array([0, 0, 0, ..., 0, 1, 0], dtype=int64)

In [60]:
email =["You've been selected for a free $500 gift card! Act fast and claim it by clicking the link below:"]
emails_count = v.transform(email)
model.predict(emails_count)

array([1], dtype=int64)

## Train the model using sklearn pipeline and reduce number of lines of code

In [61]:
from sklearn.pipeline import Pipeline

clf = Pipeline([
    ('vectorizer', CountVectorizer()),
    ('nb', MultinomialNB())
])

In [63]:
clf.fit(x_train, y_train)

Pipeline(steps=[('vectorizer', CountVectorizer()), ('nb', MultinomialNB())])

In [65]:
y_pred = clf.predict(x_test)

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.99      0.99      0.99       956
           1       0.97      0.92      0.95       159

    accuracy                           0.98      1115
   macro avg       0.98      0.96      0.97      1115
weighted avg       0.98      0.98      0.98      1115



In [66]:
clf.predict(email)

array([1], dtype=int64)